x-veld:
  code:
    description: "a fasttext training and inference jupyter notebook."
    topic:
      - "NLP"
      - "Machine Learning"
      - "word embeddings"

    input:
      - volume: /veld/input/
        file_type: "txt"
        environment_var: in_train_data_file
        description: "training data must be expressed as one sentence per line."
        content: "raw text"

    output:
      - volume: /veld/output/
        file_type:
          - "bin"
          - "fasttext model"
        environment_var: out_model_file
        content:
          - "fasttext model"
          - "word embeddings"

    config:
      - environment_var: vector_size
        description: "hyperparameter: the dimension of the vectors to be trained."
        var_type: "int"
        default: 200
      - environment_var: epochs
        description: "hyperparameter: the number of epochs of the training."
        var_type: "int"
        default: 50
      - environment_var: window_size
        description: "hyperparameter: the size of the context window of each token."
        var_type: "int"
        default: 5


services:
  veld_train:
    build: .
    command: /veld/code/train.sh
    volumes:
      - ./src/train/:/veld/code/:z
      - ./data/training_data/:/veld/input/:z
      - ./data/models/:/veld/output/:z
    environment:
      in_train_data_file: null
      out_model_file: null
      model_description: null
      vector_size: 200
      epochs: 50
      window_size: 5

