x-veld:
  code:
    description: "a fasttext training and inference jupyter notebook."
    topic:
      - "NLP"
      - "Machine Learning"
      - "word embeddings"

services:
  veld_jupyter_notebook:
    build: .
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    volumes:
      - ./src/jupyter_notebook/:/veld/code/:z
      - ./data/:/veld/storage/:z

